version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: n8n_postgres
    restart: always
    network_mode: host
    environment:
      user: "${NDN_UID:-1000}:${NDN_GID:-1000}"
      POSTGRES_USER: ${POSTGRES_USER:-n8n}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-n8n}
      POSTGRES_DB: ${POSTGRES_DB:-n8n}
      TZ: ${TZ:-America/New_York}
    volumes:
      - ./db_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    depends_on:
      - postgres
    network_mode: host
    environment:
      N8N_SECURE_COOKIE: False
      TZ: ${TZ:-America/New_York}
      N8N_HOST: ${N8N_HOST:-localhost}
      N8N_PORT: ${N8N_PORT:-5678}
      N8N_PROTOCOL: ${N8N_PROTOCOL:-http}
      # N8N on the root path requires N8N_PATH to be empty
      N8N_PATH:
      # Use your VM IP or domain from the .env file
      WEBHOOK_URL: ${WEBHOOK_URL:-https://YOUR_VM_IP:8443/}

      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: True

      # DB: Use localhost since it's on the host network
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: localhost
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB:-n8n}
      DB_POSTGRESDB_USER: ${POSTGRES_USER:-n8n}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD:-n8n}

      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY:-}
      N8N_PAYLOAD_SIZE_MAX: ${N8N_PAYLOAD_SIZE_MAX:-64}
      EXECUTIONS_MODE: ${EXECUTIONS_MODE:-regular}
    volumes:
      - n8n_data:/home/node/.n8n

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    network_mode: host
    volumes:
      - ./ollama:/root/.ollama
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 2 && ollama pull $MODEL_NAME && tail -f /dev/null"]

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: always
    depends_on:
      - ollama
    network_mode: host
    environment:
      # Ollama is available on localhost:11434
      OLLAMA_BASE_URL: http://localhost:11434
    volumes:
      - ./webui_data:/app/backend/data

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: always
    network_mode: host
    depends_on:
      - open-webui
      - n8n
      - ollama
    ports:
      # Map 8443 and 80 on the host to the container's 443 and 80
      - 0.0.0.0:8443:443
      - 0.0.0.0:80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/fullchain.pem:/etc/ssl/public.pem:ro
      - ./certs/privkey.pem:/etc/ssl/private.pem:ro
      - /opt/data/production/logs/nginx/n8n:/var/log/nginx

volumes:
  n8n_data: {}