services:
  postgres:
    image: postgres:15
    container_name: n8n_postgres
    restart: always
    environment:
      user: "${NDN_UID:-1000}:${NDN_GID:-1000}"
      POSTGRES_USER: ${POSTGRES_USER:-n8n}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-n8n}
      POSTGRES_DB: ${POSTGRES_DB:-n8n}
      TZ: ${TZ:-America/New_York}
    volumes:
      - ./db_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    depends_on:
      - postgres
    ports:
      - "5678:5678"
    environment:
      N8N_SECURE_COOKIE: False
      TZ: ${TZ:-America/New_York}
      N8N_HOST: ${N8N_HOST:-localhost}
      N8N_PORT: ${N8N_PORT:-5678}
      N8N_PROTOCOL: ${N8N_PROTOCOL:-http}
      WEBHOOK_URL: ${WEBHOOK_URL:-http://localhost:5678/}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: True
      # DB
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: localhost
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB:-n8n}
      DB_POSTGRESDB_USER: ${POSTGRES_USER:-n8n}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD:-n8n}

      # Optional
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY:-}
      N8N_PAYLOAD_SIZE_MAX: ${N8N_PAYLOAD_SIZE_MAX:-64}
      EXECUTIONS_MODE: ${EXECUTIONS_MODE:-regular}
    volumes:
      - n8n_data:/home/node/.n8n

  # --- Ollama for local LLMs (no host port; behind nginx) ---
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    network_mode: host
    volumes:
      - ./ollama:/root/.ollama
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 2 && ollama pull $MODEL_NAME && tail -f /dev/null"]

  # --- Open WebUI (served at site root /) ---
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: always
    depends_on:
      - ollama
    environment:
      OLLAMA_BASE_URL: https://ollama:11434
    volumes:
      - ./webui_data:/app/backend/data

  # --- NGINX edge (TLS, routing to /, /n8n/, /ollama/) ---
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: always
    network_mode: host
    depends_on:
      - open-webui
      - n8n
      - ollama
    ports:
      - 0.0.0.0:8443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/fullchain.pem:/etc/ssl/public.pem:ro
      - ./certs/privkey.pem:/etc/ssl/private.pem:ro
      - /opt/data/production/logs/nginx/n8n:/var/log/nginx


volumes:
  n8n_data: {}